default:
  teams:
  - devteam0
  - devteam5

user:
  blascma:
    teams:
    - devteam1
    - devteam2
    - devteam3

  userfoo:
    teams:
    - devteam1
    - devteam2
    - devteam3

group:
  "bargroup":
    teams:
    - devteam5
    - devteam8

  "foogroup":
    teams:
    - devteam6

  "bazgroup":
    teams:
    - devteam7

team:
  devteam0:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789000"
      serviceaccounts:
      - name: tiller
        namespace: foobar
      - name: tiller
        namespace: foobar2
      clusterrole: admin
    azureroleassignment:
    - principalid: "cf805c30-f000-baar-foba-6a0e4faddeea"
      role: contributor

  devteam1:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789000"
      clusterrole: admin

  devteam2:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789002"
      clusterrole: admin
    - name: "view"
      groups:
      - "cf805c30-f000-baar-foba-123456789004"
      - "cf805c30-f000-baar-foba-123456789005"
      - "cf805c30-f000-baar-foba-123456789006"
      clusterrole: admin

  devteam3:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789003"
      clusterrole: admin

  devteam4:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789004"
      clusterrole: admin

  devteam5:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789005"
      clusterrole: admin

  devteam6:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789006"
      clusterrole: admin

  devteam7:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789007"
      clusterrole: admin

  devteam8:
    k8srolebinding:
    - name: "general"
      groups:
      - "cf805c30-f000-baar-foba-123456789006"
      clusterrole: admin
