apiVersion: v1
kind: Config
preferences: {}
current-context: "k8s"

clusters:
- cluster:
    certificate-authority-data: '{{config "k8s.cluster.ca" }}'
    server: '{{config "k8s.cluster.apiserver" }}'
  name: "k8s"

contexts:
- context:
    cluster: "k8s"
    user: '{{.user.Username}}'
  name: "k8s"

users:
- name: '{{.user.Username}}'
  user:
    auth-provider:
      name: azure
      config:
        apiserver-id: '{{config "k8s.oauth.serverapp" }}'
        client-id: '{{config "k8s.oauth.clientapp" }}'
        environment: AzurePublicCloud
        tenant-id: '{{config "k8s.oauth.tenant" }}'
